services:
  - type: web
    name: msunit-web
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    envVars:
      - key: DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: msunit-postgres
          property: connectionString

databases:
  - name: msunit-postgres
    plan: free
    ipAllowList: []  # Restrict access as needed
