# Generated by Django 5.2 on 2025-05-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_patient_has_critical_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('AWAITING_REVIEW', 'Awaiting Review'), ('UNDER_CONSULTATION', 'Under Consultation'), ('CRITICAL', 'Critical'), ('STABLE', 'Stable'), ('DISCHARGED', 'Discharged')], default='REGISTERED', max_length=20),
        ),
    ]
