# Generated by Django 5.0.2 on 2025-05-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='additional_orders',
            field=models.TextField(blank=True, help_text='Additional orders such as medications, tests, or imaging studies'),
        ),
    ]
