# Generated by Django 5.0.2 on 2025-05-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_consultation_additional_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='has_critical_alert',
            field=models.BooleanField(default=False),
        ),
    ]
